[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "TextArena"
version = "0.1.3"
description = "[WIP] A Collection of Competitive Text-Based Games for Language Model Evaluation and Reinforcement Learning"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    { name="Leon Guertler", email="Guertlerlo@cfar.a-star.edu.sg" },
]
dependencies = [
    "requests",
    "aiohttp",
    "backoff",
    "rich",
    "networkx"
]

[project.urls]
"Homepage" = "https://github.com/LeonGuertler/TextArena"

[tool.poetry.include]
"textarena/*.json" = "textarena/*.json"